config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  namespace :admin do
    resources :users
    resources :sport_categories
    resources :events
  end
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :sport_category
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/sport_category.rb
class SportCategory < ApplicationRecord
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :lockable

  validates :full_name, presence: true

  has_one                         :user_information, dependent: :destroy
  accepts_nested_attributes_for   :user_information

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end
end

app/models/user_information.rb
class UserInformation < ApplicationRecord
  belongs_to :user
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :set_admin_event, only: [:show, :edit, :update, :destroy]

  # GET /admin/events
  def index
    @events = Event.all
  end

  # GET /admin/events/1
  def show
  end

  # GET /admin/events/new
  def new
    @event = Event.new
  end

  # GET /admin/events/1/edit
  def edit
  end

  # POST /admin/events
  def create
    @event = Event.new(admin_event_params)

    if @event.save
      redirect_to admin_events_path, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/events/1
  def update
    if @event.update(admin_event_params)
      redirect_to admin_events_path, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/events/1
  def destroy
    @event.destroy
    redirect_to admin_events_url, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_event_params
      params.require(:event).permit(:sport_category_id, :name, :start_date, :end_date, :status, :lat, :lang, :price)
    end
end

app/controllers/admin/sport_categories_controller.rb
class Admin::SportCategoriesController < ApplicationController
  before_action :set_admin_sport_category, only: [:show, :edit, :update, :destroy]

  # GET /admin/sport_categories
  def index
    @sport_categories = SportCategory.all
  end

  # GET /admin/sport_categories/1
  def show
  end

  # GET /admin/sport_categories/new
  def new
    @sport_category = SportCategory.new
  end

  # GET /admin/sport_categories/1/edit
  def edit
  end

  # POST /admin/sport_categories
  def create
    @sport_category = SportCategory.new(admin_sport_category_params)

    if @sport_category.save
      redirect_to admin_sport_categories_path, notice: 'Sport category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/sport_categories/1
  def update
    if @sport_category.update(admin_sport_category_params)
      redirect_to admin_sport_category_path, notice: 'Sport category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/sport_categories/1
  def destroy
    @sport_category.destroy
    redirect_to admin_sport_categories_url, notice: 'Sport category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_sport_category
      @admin_sport_category = SportCategory.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_sport_category_params
      params.require(:sport_category).permit(:name)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  include Authorization
  include BulletHelper

  protect_from_forgery with: :exception

  responders :flash
  respond_to :html

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, user_information_attributes: [:dob, :address, :phone_number]])
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    helper do
      def current_user
        super.decorate if user_signed_in?
      end
    end
  end

  private

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  end

  private

  def user_not_authorized
    redirect_to(root_path)
  end
end

app/controllers/concerns/bullet_helper.rb
module BulletHelper
  def skip_bullet
    return unless defined?(Bullet)
    return unless Bullet.enable?

    # Can't use `Bullet.enable=` b/c it's resets settings
    # https://github.com/flyerhzm/bullet/blob/master/lib/bullet.rb#L48-L58
    Bullet.instance_variable_set :@enable, false

    yield
  ensure
    Bullet.instance_variable_set :@enable, true
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController

    def new
      @user = User.new
      @user.build_user_information
    end

    def build_resource(params)
      super(resource_params)
    end

    protected

    def update_resource(resource, params)
      resource.update_attributes(params)
    end

    def account_update_params
      params = devise_parameter_sanitizer.sanitize(:account_update)

      if passwords_blank?(params)
        params.except(:password, :password_confirmation)
      else
        params
      end
    end

    def resource_params
      params.require(:user).permit(:email, :full_name, :password, :password_confirmation, user_information_attributes: [ :dob, :address, :phone_number ] )
    end

    def passwords_blank?(params)
      params[:password].blank? && params[:password_confirmation].blank?
    end
  end
end

app/views/admin/events/_form.html.slim
= form_for [:admin, @event] do |f|
  - if @event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@admin_event.errors.count, "error")} prohibited this admin_event from being saved:"
      ul
        - @admin_event.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :sport_category_id
    = f.select :sport_category_id, options_for_select(SportCategory.all.collect {|p| [ p.name, p.id ] }, { include_blank: true })
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :start_date
    = f.datetime_select :start_date
  .field
    = f.label :end_date
    = f.datetime_select :end_date
  .field
    = f.label :status
    = f.check_box :status
  .field
    = f.label :lat
    = f.text_field :lat
  .field
    = f.label :lang
    = f.text_field :lang
  .field
    = f.label :price
    = f.text_field :price
  .actions = f.submit

app/views/admin/events/edit.html.slim
h1 Editing Event

== render 'form'

=> link_to 'Show', @admin_event
'|
=< link_to 'Back', admin_events_path

app/views/admin/events/index.html.slim
h1 Listing admin_events

table
  thead
    tr
      th Sport category
      th Name
      th Start date
      th End date
      th Status
      th Lat
      th Lang
      th Price
      th
      th
      th

  tbody
    - @events.each do |admin_event|
      tr
        td = admin_event.sport_category_id
        td = admin_event.name
        td = admin_event.start_date
        td = admin_event.end_date
        td = admin_event.status
        td = admin_event.lat
        td = admin_event.lang
        td = admin_event.price
        td = link_to 'Edit', edit_admin_event_path(admin_event)
        td = link_to 'Destroy', admin_event_path(admin_event), data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Event', new_admin_event_path

app/views/admin/events/new.html.slim
h1 New Event

== render 'form'

= link_to 'Back', admin_events_path

app/views/admin/events/show.html.slim
p#notice = notice

p
  strong Sport category:
  = @admin_event.sport_category_id
p
  strong Name:
  = @admin_event.name
p
  strong Start date:
  = @admin_event.start_date
p
  strong End date:
  = @admin_event.end_date
p
  strong Status:
  = @admin_event.status
p
  strong Lat:
  = @admin_event.lat
p
  strong Lang:
  = @admin_event.lang
p
  strong Price:
  = @admin_event.price

=> link_to 'Edit', edit_admin_event_path(@admin_event)
'|
=< link_to 'Back', admin_events_path

app/views/admin/sport_categories/_form.html.slim
= form_for [:admin,@sport_category] do |f|
  - if @sport_category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@sport_category.errors.count, "error")} prohibited this admin_sport_category from being saved:"
      ul
        - @sport_category.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/admin/sport_categories/edit.html.slim
h1 Editing admin_sport_category

== render 'form'

=> link_to 'Show', @admin_sport_category
'|
=< link_to 'Back', admin_sport_categories_path

app/views/admin/sport_categories/index.html.slim
h1 Listing Sport Category

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @sport_categories.each do |admin_sport_category|
      tr
        td = admin_sport_category.name
        td = link_to 'Edit', edit_admin_sport_category_path(admin_sport_category)

br

= link_to 'New Sport category', new_admin_sport_category_path

app/views/admin/sport_categories/new.html.slim
h1 New admin_sport_category

== render 'form'

= link_to 'Back', admin_sport_categories_path

app/views/admin/sport_categories/show.html.slim
p#notice = notice

p
  strong Name:
  = @admin_sport_category.name

=> link_to 'Edit', edit_admin_sport_category_path(@admin_sport_category)
'|
=< link_to 'Back', admin_sport_categories_path

app/views/admin/users/index.html.erb
<div class="ks-page-header">
  <section class="ks-title-and-subtitle">
    <div class="ks-title-block">
      <h3 class="ks-main-title">List User</h3>
    </div>
  </section>
</div>

<div class="ks-page-content">
  <div class="ks-page-content-body ks-content-nav">
    <div class="ks-nav-body">
      <div class="ks-nav-body-wrapper">
        <div class="container-fluid">
          <div class="bootstrap-table">
            <div class="ks-controls">
              <br/><br/><br/>
            </div>
            <table class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                <th>Name</th>
                <th>Address</th>
                <th>Phone number</th>
                <th>Email</th>
                <th colspan="3"></th>
              </tr>
              </thead>

              <tbody>
              <% @users.each do |user| %>
                  <tr>
                    <td><%= user.full_name %></td>
                    <td><%= user.user_information.address %></td>
                    <td><%= user.user_information.phone_number %></td>
                    <td><%= user.email %></td>
                    <td>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_footer.html.slim
footer.row
  .columns

app/views/application/_messages.html.slim
- flash.each do |type, content|
  div(class="callout #{type}" data-closable)
    = content
    button.close-button(tabindex="0" aria-label="Dismiss alert" type="button" data-close)
      span aria-hidden="true" &times;

app/views/application/_navigation.html.slim
.title-bar data-hide-for="medium" data-responsive-toggle="navigation_menu"
  button.menu-icon data-toggle="" type="button"
  title-bar-title Menu

nav.top-bar#navigation_menu
  = render "navigation_main"
  = render "navigation_user"

app/views/application/_navigation_main.html.slim
.top-bar-left
  ul.menu
    - if user_signed_in?
      = active_link_to "Home", root_path, active: :exclusive, wrap_tag: :li

app/views/application/_navigation_user.html.slim
ul.top-bar-right.menu.dropdown(data-dropdown-menu)
  - if user_signed_in?
    li
      a = current_user.full_name
      ul.menu
        li = link_to "Edit profile", edit_user_registration_path
        li = link_to "Sign out", destroy_user_session_path
  - else
    = active_link_to "Sign in", new_user_session_path, active: :exclusive, wrap_tag: :li
    = active_link_to "Sign up", new_user_registration_path, active: :exclusive, wrap_tag: :li

app/views/layouts/application.html.slim
doctype html

html class="no-js" lang="en"

  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="robots" content="NOODP,NOYDIR"

    = display_meta_tags site: "RailsBase", keywords: %w(title site)
    = csrf_meta_tags

    = stylesheet_link_tag :application

    = javascript_tag "window.App = {}"

    == analytics_init if GoogleAnalytics.valid_tracker?

  body
    = render "navigation"
    = render "messages"

    main.container
      = yield

    = render "footer"

    javascript:
      App.currentUserData = #{{current_user.to_json}};

    = javascript_include_tag :application

app/views/pages/home.html.slim
.row
  .columns
    h2
      = title("Home")

app/views/users/shared/_links.html.slim
h6 Anything else?
ul.no-bullet
  - if controller_name != "sessions"
    li = link_to "Sign in", new_session_path(resource_name)

  - if devise_mapping.registerable? && controller_name != "registrations"
    li = link_to "Create a new account", new_registration_path(resource_name)

  - if devise_mapping.recoverable? && controller_name != "passwords"
    li = link_to "Forgot your password?", new_password_path(resource_name)

  - if devise_mapping.confirmable? && controller_name != "confirmations"
    li = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)

  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks"
    li = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)

  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      li = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)